### ISSUE TITLE
PyPy 7.3.18 fails to build with GCC 14

### ISSUE THREAD

**Issue by mgorny** [pypy/pypy#5194]
```
x86_64-pc-linux-gnu-gcc -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused -Wno-address -Wno-discarded-qualifiers -Wno-duplicate-decl-specifier -march=znver2 --param=l1-cache-size=32 --param=l1-cache-line-size=64 -O2 -pipe -frecord-gcc-switches -flto=jobserver  -DPy_BUILD_CORE -DPYPY_JIT_CODEMAP -DPy_BUILD_CORE -DRPYTHON_VMPROF -DVMPROF_UNIX -DVMPROF_LINUX -DPy_BUILD_CORE -DRPYTHON_VMPROF=1 -DRPYTHON_VMPROF=1 -DRPYTHON_VMPROF=1 -DPYPY_CPU_HAS_STANDARD_PRECISION -DPy_BUILD_CORE -DPYPY_MAKEFILE  -o vmp_stack.o -c vmp_stack.c -I"/tmp/portage/dev-python/pypy-exe-7.3.18/work/pypy2.7-v7.3.18-src/rpython"/translator/c -I.. -I"/tmp/portage/dev-python/pypy-exe-7.3.18/work/pypy2.7-v7.3.18-src/rpython"/../pypy/module/cpyext/include -I"/tmp/portage/dev-python/pypy-exe-7.3.18/work/pypy2.7-v7.3.18-src/rpython"/../pypy/module/cpyext/parse -I/usr/lib64/libffi/include -I"/tmp/portage/dev-python/pypy-exe-7.3.18/work/pypy2.7-v7.3.18-src/rpython"/../pypy/module/_multibytecodec -I"/tmp/portage/dev-python/pypy-exe-7.3.18/work/pypy2.7-v7.3.18-src/rpython"/rlib/rjitlog/src -I"/tmp/portage/dev-python/pypy-exe-7.3.18/work/pypy2.7-v7.3.18-src/rpython"/rlib/rvmprof/src -I"/tmp/portage/dev-python/pypy-exe-7.3.18/work/pypy2.7-v7.3.18-src/rpython"/rlib/rvmprof/src/shared -I"/tmp/portage/dev-python/pypy-exe-7.3.18/work/pypy2.7-v7.3.18-src/rpython"/rlib/rvmprof/src/shared/libbacktrace -I"/tmp/portage/dev-python/pypy-exe-7.3.18/work/pypy2.7-v7.3.18-src/rpython"/../pypy/module/_cffi_backend/src -I/usr/include/ncursesw -I"/tmp/portage/dev-python/pypy-exe-7.3.18/work/pypy2.7-v7.3.18-src/rpython"/../pypy/module/faulthandler -I"/tmp/portage/dev-python/pypy-exe-7.3.18/work/pypy2.7-v7.3.18-src/rpython"/../pypy/module/operator 
vmp_stack.c: In function ‘_write_python_stack_entry’:
vmp_stack.c:161:51: error: passing argument 1 of ‘vmprof_write_header_for_jit_addr’ from incompatible pointer type [-Wincompatible-pointer-types]
  161 |         *depth = vmprof_write_header_for_jit_addr(result, *depth, pc, max_depth);
      |                                                   ^~~~~~
      |                                                   |
      |                                                   void **
In file included from /tmp/portage/dev-python/pypy-exe-7.3.18/work/pypy2.7-v7.3.18-src/rpython/rlib/rvmprof/src/shared/vmprof.h:59,
                 from /tmp/portage/dev-python/pypy-exe-7.3.18/work/pypy2.7-v7.3.18-src/rpython/rlib/rvmprof/src/shared/vmp_stack.h:3,
                 from vmp_stack.c:1:
/tmp/portage/dev-python/pypy-exe-7.3.18/work/pypy2.7-v7.3.18-src/rpython/rlib/rvmprof/src/rvmprof.h:44:49: note: expected ‘intptr_t *’ {aka ‘long int *’} but argument is of type ‘void **’
   44 | long vmprof_write_header_for_jit_addr(intptr_t *result, long n,
      |                                       ~~~~~~~~~~^~~~~~
vmp_stack.c: In function ‘vmp_walk_and_record_stack’:
vmp_stack.c:500:54: error: passing argument 1 of ‘vmprof_write_header_for_jit_addr’ from incompatible pointer type [-Wincompatible-pointer-types]
  500 |             depth = vmprof_write_header_for_jit_addr(result, depth, pc, max_depth);
      |                                                      ^~~~~~
      |                                                      |
      |                                                      void **
/tmp/portage/dev-python/pypy-exe-7.3.18/work/pypy2.7-v7.3.18-src/rpython/rlib/rvmprof/src/rvmprof.h:44:49: note: expected ‘intptr_t *’ {aka ‘long int *’} but argument is of type ‘void **’
   44 | long vmprof_write_header_for_jit_addr(intptr_t *result, long n,
      |                                       ~~~~~~~~~~^~~~~~
make: *** [Makefile:945: vmp_stack.o] Error 1
make: *** Waiting for unfinished jobs....
```

There's also a lot of warnings about `PATH_MAX` being redefined, e.g.:

```
In file included from singleheader.h:134,
                 from rpython_translator.c:4:
/tmp/portage/dev-python/pypy-exe-7.3.18/work/pypy2.7-v7.3.18-src/rpython/translator/c/src/signals.h:26:9: warning: "PATH_MAX" redefined
   26 | #define PATH_MAX 1024
      |         ^~~~~~~~
In file included from /usr/include/bits/local_lim.h:38,
                 from /usr/include/bits/posix1_lim.h:161,
                 from /usr/include/limits.h:195,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/limits.h:210,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/syslimits.h:7,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/limits.h:34,
                 from /tmp/portage/dev-python/pypy-exe-7.3.18/work/pypy2.7-v7.3.18-src/rpython/../pypy/module/cpyext/include/Python.h:1
0,
                 from singleheader.h:113:
/usr/include/linux/limits.h:13:9: note: this is the location of the previous definition
   13 | #define PATH_MAX        4096    /* # chars in a path name including nul */
      |         ^~~~~~~~
```

**Comment by cfbolz** [comment]
@mgorny thanks for the report, sorry, both of them we should clearly have caught ourselves :-(. Could you let me know whether the two patches fix things for you?

**Comment by mgorny** [comment]
Testing.

**Comment by stefanor** [comment]
One more:

```
_sqlite3_cffi.c: In function ‘_cffi_d_sqlite3_serialize’:
_sqlite3_cffi.c:5104:36: error: passing argument 3 of ‘sqlite3_serialize’ from incompatible pointer type [-Wincompatible-pointer-types]
 5104 |   return sqlite3_serialize(x0, x1, x2, x3);
      |                                    ^~
      |                                    |
      |                                    int64_t * {aka long int *}
In file included from _sqlite3_cffi.c:574:
/usr/include/sqlite3.h:10727:18: note: expected ‘sqlite3_int64 *’ {aka ‘long long int *’} but argument is of type ‘int64_t *’ {aka ‘long int *’}
10727 |   sqlite3_int64 *piSize, /* Write size of the DB here, if not NULL */
      |   ~~~~~~~~~~~~~~~^~~~~~
```

**Comment by mattip** [comment]
Fixed sqlite3 cffi build in 634a0b37b1fd9e for py3.11

**Comment by mattip** [comment]
I wonder if we should turn on those gcc14 warning-to-error flags by default. If I recall correctly, I tried this but it makes some untranslated tests fail. https://github.com/pypy/pypy/blob/1a0d436048e57e222227d72256d24593f615e457/rpython/translator/platform/linux.py#L21-L24

I should finish #5101 which would clean up some of the problems.

**Comment by mgorny** [comment]
> [@mgorny](https://github.com/mgorny) thanks for the report, sorry, both of them we should clearly have caught ourselves :-(. Could you let me know whether the two patches fix things for you?

As noted on IRC, it helped. Thanks!

**Comment by stefanor** [comment]
> Fixed sqlite3 cffi build in https://github.com/pypy/pypy/commit/634a0b37b1fd9e7554309eca46d9459a396393e3 for py3.11

@mattip: Not enough, I'm afraid.

```
_sqlite3_cffi.c: In function ‘_cffi_d_sqlite3_serialize’:
_sqlite3_cffi.c:5095:36: error: passing argument 3 of ‘sqlite3_serialize’ from incompatible po
inter type [-Wincompatible-pointer-types]
 5095 |   return sqlite3_serialize(x0, x1, x2, x3);
      |                                    ^~
      |                                    |
      |                                    int64_t * {aka long int *}
In file included from _sqlite3_cffi.c:574:
/usr/include/sqlite3.h:10727:18: note: expected ‘sqlite3_int64 *’ {aka ‘long long int *’} but 
argument is of type ‘int64_t *’ {aka ‘long int *’}
10727 |   sqlite3_int64 *piSize, /* Write size of the DB here, if not NULL */
      |   ~~~~~~~~~~~~~~~^~~~~~
Traceback (most recent call last):
  File "/build/reproducible-path/pypy3-7.3.18+dfsg/lib-python/3/distutils/unixccompiler.py", l
ine 117, in _compile
    self.spawn(compiler_so + cc_args + [src, '-o', obj] +
  File "/build/reproducible-path/pypy3-7.3.18+dfsg/lib-python/3/distutils/ccompiler.py", line 
910, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/build/reproducible-path/pypy3-7.3.18+dfsg/lib-python/3/distutils/spawn.py", line 91, 
in spawn
    raise DistutilsExecError(
distutils.errors.DistutilsExecError: command '/usr/bin/gcc' failed with exit code 1
```

**Comment by mgorny** [comment]
@stefanor, could you try #5200?

**Comment by stefanor** [comment]
@mgorny: Yep, that looks good.

**Comment by cfbolz** [comment]
we got all of the problems, right? I'm closing, please reopen if we missed something. Thanks for the report and PRs everyone!
