### ISSUE TITLE
pip install numpy fails on PyPy 5.3 on OS X

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#2319]
In Heptapod by bitbucket_importer on Jun 9, 2016, 10:01

*Created originally on Bitbucket by [kostialopuhin (Konstantin Lopukhin)](https://bitbucket.org/[7.3.7](https://github.com/gitlab-importer/pypy/milestone/7)Bfb5fb8d6-dae1-45a4-8286-947e3578011e%7D/)*

The error is ``AttributeError: 'module' object has no attribute 'get_makefile_filename'``, which is similar to #1636. The same steps work on Ubuntu for pypy 5.3, and ``pip install numpy`` works under CPython 2.7 on the same OS X. I attached the full log. It could be specific to my machine / compilers available, shall I try to get more info?

 *Attachments:* [numpy-osx-log.txt](https://pypy-attachments.s3.amazonaws.com/736937129/26a3ed14c4edb7d3801342ea79e47a62e331e6fccbd94638fdaaef1bc70ed1d1/numpy-osx-log.txt)
