### ISSUE TITLE
PySlice_Unpack usable in CPython >= 3.6.1

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#3101]
In Heptapod by bitbucket_importer on Oct 25, 2019, 23:09

*Created originally on Bitbucket by [paugier (Pierre Augier)](https://bitbucket.org/[7.3.7](https://github.com/gitlab-importer/pypy/milestone/7)Beb327c54-cadd-4fce-9edd-f8fe047a9b93%7D/)*

With PyPy3.6 \(7.2\), I get the error `pythran/pythonic/types/slice.hpp:502:3: error: use of undeclared identifier 'PySlice_Unpack'`.

In pythonic/types/slice.hpp, there is

```c++
#if PY_MAJOR_VERSION > 3 || (PY_MAJOR_VERSION == 3 && PY_MINOR_VERSION > 6) || \
    (PY_MAJOR_VERSION == 3 && PY_MINOR_VERSION == 6 && PY_MICRO_VERSION >= 1)
  PySlice_Unpack(obj, &start, &stop, &step);
#elif PY_MAJOR_VERSION == 3 && PY_MINOR_VERSION >= 1
  PySlice_GetIndices((PyObject *)obj, PY_SSIZE_T_MAX, &start, &stop, &step);
#else
  PySlice_GetIndices((PySliceObject *)obj, PY_SSIZE_T_MAX, &start, &stop,
                     &step);
#endif
```

Note that this code of course works in CPython 3.6.

In the documentation for CPython 3.6, `PySlice_Unpack` is not mentioned, so it seems that it is not really a PyPy bug \(?\)

[https://docs.python.org/3.6/c-api/slice.html](https://docs.python.org/3.6/c-api/slice.html)

`PySlice_Unpack` is mentioned in [https://docs.python.org/3.7/c-api/slice.html](https://docs.python.org/3.7/c-api/slice.html)

\(See [https://github.com/serge-sans-paille/pythran/issues/1395](https://github.com/serge-sans-paille/pythran/issues/1395)\)

I submit a quick and dirty PR for Pythran to fix this [https://github.com/serge-sans-paille/pythran/pull/1397](https://github.com/serge-sans-paille/pythran/pull/1397)

What would be the right way to do that for PyPy3.6 7.2? Is there a PyPy-specific macro defined in the PyPy headers?

‌
