### ISSUE TITLE
pypy 7.3.10 MacOS x86_64 release do not work on macOS 10.15.7

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#3864]
In Heptapod by @rndblnch on Dec 8, 2022, 09:10

the 7.3.10 MacOS x86_64 release is advertised as MacOS >= 10.14 on https://www.pypy.org/download.html

attempting to run pypy2.7, pypy3.8 or pypy3.9 on Catalina (macOS 10.15.7) all give the same error:

```
% ./pypy3.9-v7.3.10-macos_x86_64/bin/pypy
Python 3.9.15 (21401ebc2df332b6be6e3d364a985e951a72bbbd, Dec 05 2022, 18:37:32)
[PyPy 7.3.10 with GCC Apple LLVM 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
dyld: lazy symbol binding failed: Symbol not found: _pthread_jit_write_protect_np
  Referenced from: /Users/Shared/src/pypy3.9-v7.3.10-macos_x86_64/bin/libpypy3.9-c.dylib
  Expected in: flat namespace

dyld: Symbol not found: _pthread_jit_write_protect_np
  Referenced from: /Users/Shared/src/pypy3.9-v7.3.10-macos_x86_64/bin/libpypy3.9-c.dylib
  Expected in: flat namespace

Abort
```
