### ISSUE TITLE
Numpy fails to compile on MacOS with PyPy 3.8 (7.3.7)

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#3621]
In Heptapod by @lithomas1 on Dec 22, 2021, 23:50

There is a warning when compiling numpy on macOS x86_64 with clang
In file included from /tmp/pypy3.8-v7.3.7-osx64/include/pypy3.8/Python.h:73:
/tmp/pypy3.8-v7.3.7-osx64/include/pypy3.8/pyport.h:68:20: \
    error: redefinition of typedef 'Py_hash_t' is a C11 feature [-Werror,-Wtypedef-redefinition]
typedef Py_ssize_t Py_hash_t;
                       ^
/tmp/pypy3.8-v7.3.7-osx64/include/pypy3.8/cpyext_object.h:9:14: \
    note: previous definition is here
    typedef long Py_hash_t;
                 ^
1 error generated.

Cross-posted from https://github.com/numpy/numpy/pull/20528#issuecomment-988099113
cc @mattip
