### ISSUE TITLE
AttributeError: 'thread.RLock' object has no attribute '_RLock__block'

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#2969]
In Heptapod by bitbucket_importer on Mar 7, 2019, 03:53

*Created originally on Bitbucket by [allen (qingliang xiong)](https://bitbucket.org/[7.3.7](https://github.com/gitlab-importer/pypy/milestone/7)Bd348b54f-3166-4546-bd02-845e796cd40d%7D/)*

My test code is worked fine with original Python 2.7.x, but break on PyPy v7.0, the traceback  is shown below:
```
Traceback (most recent call last):
  File "/home/xqliang/work/profile2/.tox/pypy/bin/pytest", line 10, in <module>
    sys.exit(main())
  File "/home/xqliang/work/profile2/.tox/pypy/site-packages/_pytest/config.py", line 49, in main
    config = _prepareconfig(args, plugins)
  File "/home/xqliang/work/profile2/.tox/pypy/site-packages/_pytest/config.py", line 164, in _prepareconfig
    pluginmanager=pluginmanager, args=args)
  File "/home/xqliang/work/profile2/.tox/pypy/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/xqliang/work/profile2/.tox/pypy/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/xqliang/work/profile2/.tox/pypy/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/home/xqliang/work/profile2/.tox/pypy/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/home/xqliang/work/profile2/.tox/pypy/site-packages/_pytest/vendored_packages/pluggy.py", line 250, in _wrapped_call
    wrap_controller.send(call_outcome)
  File "/home/xqliang/work/profile2/.tox/pypy/site-packages/_pytest/helpconfig.py", line 67, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/home/xqliang/work/profile2/.tox/pypy/site-packages/_pytest/vendored_packages/pluggy.py", line 280, in get_result
    _reraise(*ex)  # noqa
  File "/home/xqliang/work/profile2/.tox/pypy/site-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__
    self.result = func()
  File "/home/xqliang/work/profile2/.tox/pypy/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/home/xqliang/work/profile2/.tox/pypy/site-packages/_pytest/config.py", line 934, in pytest_cmdline_parse
    self.parse(args)
  File "/home/xqliang/work/profile2/.tox/pypy/site-packages/_pytest/config.py", line 1106, in parse
    self._preparse(args, addopts=addopts)
  File "/home/xqliang/work/profile2/.tox/pypy/site-packages/_pytest/config.py", line 1077, in _preparse
    args=args, parser=self._parser)
  File "/home/xqliang/work/profile2/.tox/pypy/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/xqliang/work/profile2/.tox/pypy/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/xqliang/work/profile2/.tox/pypy/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/home/xqliang/work/profile2/.tox/pypy/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/home/xqliang/work/profile2/.tox/pypy/site-packages/_pytest/vendored_packages/pluggy.py", line 254, in _wrapped_call
    return call_outcome.get_result()
  File "/home/xqliang/work/profile2/.tox/pypy/site-packages/_pytest/vendored_packages/pluggy.py", line 280, in get_result
    _reraise(*ex)  # noqa
  File "/home/xqliang/work/profile2/.tox/pypy/site-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__
    self.result = func()
  File "/home/xqliang/work/profile2/.tox/pypy/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/home/xqliang/work/profile2/.tox/pypy/site-packages/nameko/testing/pytest.py", line 47, in pytest_load_initial_conftests
    eventlet.monkey_patch()
  File "/home/xqliang/work/profile2/.tox/pypy/site-packages/eventlet/patcher.py", line 265, in monkey_patch
    _green_existing_locks()
  File "/home/xqliang/work/profile2/.tox/pypy/site-packages/eventlet/patcher.py", line 360, in _green_existing_locks
    isinstance(obj._RLock__block, lock_type)):
AttributeError: 'thread.RLock' object has no attribute '_RLock__block'
```

~~~
$ python
Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from threading import RLock
>>> dir(RLock())
['_RLock__block', '_RLock__count', '_RLock__owner', '_Verbose__verbose', '__class__', '__delattr__', '__dict__', '__doc__', '__enter__', '__exit__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_acquire_restore', '_is_owned', '_note', '_release_save', 'acquire', 'release']
>>>> import eventlet
>>>> eventlet.__version__
'0.24.1'
~~~

~~~
$ pypy
Python 2.7.13 (9112c8071614, Feb 05 2019, 13:50:00)
[PyPy 7.0.0 with GCC 6.2.0 20160901] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>> from threading import RLock
>>>> dir(RLock())
['__class__', '__delattr__', '__doc__', '__enter__', '__exit__', '__format__', '__getattribute__', '__hash__', '__init__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__str__', '__subclasshook__', '__weakref__', '_acquire_restore', '_is_owned', '_note', '_release_save', 'acquire', 'release']
>>>> import eventlet
>>>> eventlet.__version__
'0.24.1'
~~~

As mentioned above, PyPy RLock missing some attributes: 
`['_RLock__block', '_RLock__count', '_RLock__owner', '_Verbose__verbose', '__dict__', '__module__', '__sizeof__']`
