### ISSUE TITLE
7.3.18: potential regression causing Cython distutils code to run compiler from `__pycache__` directory

### ISSUE THREAD

**Issue by mgorny** [pypy/pypy#5233]
Gotta investigate it further but basically:

install system `lmdb` library first, then:

```sh
git clone https://github.com/jnwatson/py-lmdb/
cd py-lmdb
pypy3.10 -m venv .venv
. .venv/bin/activate
pip install cython setuptools
python setup.py build
```

It works with PyPy3.10 7.3.17 but fails with PyPy3.10 (and 3.11) 7.3.19:

<details>
<summary>lmdb_cffi.c:62:14: fatal error: preload.h: No such file or directory</summary>

```pytb
py-lmdb: Using system version of liblmdb.
Using cffi extension.
lmdb_cffi.c:62:14: fatal error: preload.h: No such file or directory
   62 |     #include "preload.h"
      |              ^~~~~~~~~~~
compilation terminated.
Traceback (most recent call last):
  File "/tmp/py-lmdb/lmdb/__init__.py", line 41, in <module>
    raise ImportError
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/py-lmdb/.venv/lib/pypy3.10/site-packages/setuptools/_distutils/unixccompiler.py", line 186, in _compile
    self.spawn(compiler_so + cc_args + [src, '-o', obj] + extra_postargs)
  File "/tmp/py-lmdb/.venv/lib/pypy3.10/site-packages/setuptools/_distutils/ccompiler.py", line 1007, in spawn
    spawn(cmd, dry_run=self.dry_run, **kwargs)
  File "/tmp/py-lmdb/.venv/lib/pypy3.10/site-packages/setuptools/_distutils/spawn.py", line 70, in spawn
    raise DistutilsExecError(
distutils.errors.DistutilsExecError: command '/usr/bin/gcc' failed with exit code 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/pypy3.10-v7.3.19-linux64/lib/pypy3.10/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/tmp/py-lmdb/.venv/lib/pypy3.10/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/tmp/py-lmdb/.venv/lib/pypy3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/tmp/py-lmdb/.venv/lib/pypy3.10/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/tmp/py-lmdb/.venv/lib/pypy3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
    self.build_extensions()
  File "/tmp/py-lmdb/.venv/lib/pypy3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 466, in build_extensions
    self._build_extensions_serial()
  File "/tmp/py-lmdb/.venv/lib/pypy3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 492, in _build_extensions_serial
    self.build_extension(ext)
  File "/tmp/py-lmdb/.venv/lib/pypy3.10/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "/tmp/py-lmdb/.venv/lib/pypy3.10/site-packages/Cython/Distutils/build_ext.py", line 135, in build_extension
    super(build_ext, self).build_extension(ext)
  File "/tmp/py-lmdb/.venv/lib/pypy3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 547, in build_extension
    objects = self.compiler.compile(
  File "/tmp/py-lmdb/.venv/lib/pypy3.10/site-packages/setuptools/_distutils/ccompiler.py", line 599, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/tmp/py-lmdb/.venv/lib/pypy3.10/site-packages/setuptools/_distutils/unixccompiler.py", line 188, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command '/usr/bin/gcc' failed with exit code 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/py-lmdb/setup.py", line 180, in <module>
    import lmdb.cffi
  File "/tmp/py-lmdb/lmdb/__init__.py", line 48, in <module>
    from lmdb.cffi import *
  File "/tmp/py-lmdb/lmdb/cffi.py", line 372, in <module>
    _lib = _ffi.verify(_CFFI_VERIFY,
  File "/tmp/pypy3.10-v7.3.19-linux64/lib/pypy3.10/cffi/api.py", line 468, in verify
    lib = self.verifier.load_library()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/pypy3.10-v7.3.19-linux64/lib/pypy3.10/cffi/verifier.py", line 105, in load_library
    self._compile_module()
  File "/tmp/pypy3.10-v7.3.19-linux64/lib/pypy3.10/cffi/verifier.py", line 209, in _compile_module
    output_rel_filename = ffiplatform.compile(tmpdir, self.get_extension())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/pypy3.10-v7.3.19-linux64/lib/pypy3.10/cffi/ffiplatform.py", line 20, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/pypy3.10-v7.3.19-linux64/lib/pypy3.10/cffi/ffiplatform.py", line 57, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.VerificationError: CompileError: command '/usr/bin/gcc' failed with exit code 1
```
</details>

Placing a strategic `ValueError` points out that `getcwd()` is inside the `__pycache__` directory now:

<details>
<summary>ValueError: /tmp/py-lmdb/lmdb/__pycache__</summary>

```pytb
py-lmdb: Using system version of liblmdb.
Using cffi extension.
Traceback (most recent call last):
  File "/tmp/py-lmdb/lmdb/__init__.py", line 41, in <module>
    raise ImportError
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/py-lmdb/setup.py", line 180, in <module>
    import lmdb.cffi
  File "/tmp/py-lmdb/lmdb/__init__.py", line 48, in <module>
    from lmdb.cffi import *
  File "/tmp/py-lmdb/lmdb/cffi.py", line 372, in <module>
    _lib = _ffi.verify(_CFFI_VERIFY,
  File "/tmp/pypy3.10-v7.3.19-linux64/lib/pypy3.10/cffi/api.py", line 468, in verify
    lib = self.verifier.load_library()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/pypy3.10-v7.3.19-linux64/lib/pypy3.10/cffi/verifier.py", line 105, in load_library
    self._compile_module()
  File "/tmp/pypy3.10-v7.3.19-linux64/lib/pypy3.10/cffi/verifier.py", line 209, in _compile_module
    output_rel_filename = ffiplatform.compile(tmpdir, self.get_extension())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/pypy3.10-v7.3.19-linux64/lib/pypy3.10/cffi/ffiplatform.py", line 20, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/pypy3.10-v7.3.19-linux64/lib/pypy3.10/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/tmp/py-lmdb/.venv/lib/pypy3.10/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/tmp/py-lmdb/.venv/lib/pypy3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/tmp/py-lmdb/.venv/lib/pypy3.10/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/tmp/py-lmdb/.venv/lib/pypy3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
    self.build_extensions()
  File "/tmp/py-lmdb/.venv/lib/pypy3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 466, in build_extensions
    self._build_extensions_serial()
  File "/tmp/py-lmdb/.venv/lib/pypy3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 492, in _build_extensions_serial
    self.build_extension(ext)
  File "/tmp/py-lmdb/.venv/lib/pypy3.10/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "/tmp/py-lmdb/.venv/lib/pypy3.10/site-packages/Cython/Distutils/build_ext.py", line 135, in build_extension
    super(build_ext, self).build_extension(ext)
  File "/tmp/py-lmdb/.venv/lib/pypy3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 547, in build_extension
    objects = self.compiler.compile(
  File "/tmp/py-lmdb/.venv/lib/pypy3.10/site-packages/setuptools/_distutils/ccompiler.py", line 599, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/tmp/py-lmdb/.venv/lib/pypy3.10/site-packages/setuptools/_distutils/unixccompiler.py", line 186, in _compile
    self.spawn(compiler_so + cc_args + [src, '-o', obj] + extra_postargs)
  File "/tmp/py-lmdb/.venv/lib/pypy3.10/site-packages/setuptools/_distutils/ccompiler.py", line 1007, in spawn
    spawn(cmd, dry_run=self.dry_run, **kwargs)
  File "/tmp/py-lmdb/.venv/lib/pypy3.10/site-packages/setuptools/_distutils/spawn.py", line 56, in spawn
    raise ValueError(os.getcwd())
ValueError: /tmp/py-lmdb/lmdb/__pycache__
```
</details>

I've also confirmed that:
- the directory is correct prior to `_ffi.verify()` call
- the problem appears only if Cython is installed

So my guess is that `/tmp/py-lmdb/.venv/lib/pypy3.10/site-packages/Cython/Distutils/build_ext.py` messes up the current directory. However, since the problem didn't appear with prior PyPy3.10 versions, I'm guessing something changed on PyPy end.

I'm going to investigate this further later on.

**Comment by mgorny** [comment]
Okay, I did something wrong before and now can reproduce without Cython too.

**Comment by mgorny** [comment]
Bisected it to 92f4424babb776bacced3304ad69eb7c0781ec75. Reverting all the `cffi` changes including this one fixes the build.

Looks like the code tries hard to adjust paths for the changed cwd, but it doesn't account e.g. for `-I` and similar options.

CC @mattip

**Comment by mattip** [comment]
Thanks for the bisect, sorry for the mess. I think this was an adaptation of https://github.com/python-cffi/cffi/pull/135. I think we can just back it out, and wait for someone to report an issue with too-long file names on windows.

**Comment by mgorny** [comment]
No problem. Glad I caught it before it actually landed in CFFI.
