### ISSUE TITLE
Missing __self__ from super objects

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#2385]
In Heptapod by bitbucket_importer on Aug 30, 2016, 11:22

*Created originally on Bitbucket by [david_maciver_ (David MacIver)](https://bitbucket.org/[7.3.7](https://github.com/gitlab-importer/pypy/milestone/7)Bb847790a-6381-484a-b7fb-02218c52f3f2%7D/)*

```python
class Foo(object):
    pass

x = Foo()

assert super(Foo, x).__self__ is x
```

This works on CPython 2.7 but on pypy 5.3.1 it errors with 

```
Traceback (most recent call last):
  File "superior.py", line 6, in <module>
    assert super(Foo, x).__self__ is x
AttributeError: 'super' object has no attribute '__self__'
```

What's weird is this seems to be a regression. I don't currently have an old pypy around to test on but I found this because code that was working on pypy 2.6.1 started breaking when I upgraded my build to 5.3.1
