### ISSUE TITLE
Latest 3.10 nighly build breaks building wheel for kiwisolver

### ISSUE THREAD

**Issue by skirpichev** [pypy/pypy#5004]
Traceback from [this build log](https://github.com/mpmath/mpmath/actions/runs/10381623887/job/28743344543?pr=839):
<details>

```
× Building wheel for kiwisolver (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [86 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
  Building wheel for numpy (pyproject.toml): started
      creating build/lib.linux-x86_64-pypy310
      creating build/lib.linux-x86_64-pypy310/kiwisolver
      copying py/kiwisolver/exceptions.py -> build/lib.linux-x86_64-pypy310/kiwisolver
      copying py/kiwisolver/__init__.py -> build/lib.linux-x86_64-pypy310/kiwisolver
      copying py/kiwisolver/_cext.pyi -> build/lib.linux-x86_64-pypy310/kiwisolver
      copying py/kiwisolver/py.typed -> build/lib.linux-x86_64-pypy310/kiwisolver
      running build_ext
      building 'kiwisolver._cext' extension
      creating build/temp.linux-x86_64-pypy310
      creating build/temp.linux-x86_64-pypy310/py
      creating build/temp.linux-x86_64-pypy310/py/src
      g++ -pthread -DNDEBUG -O2 -fPIC -I/tmp/pip-build-env-9l5f03w9/overlay/lib/pypy3.10/site-packages/cppy/include -I. -I/home/runner/work/_temp/b89c2904-6e90-4eaf-9a37-51acc283b398/pypy-c-jit-185000-7d940def6f6b-linux64/include/pypy3.10 -c py/src/constraint.cpp -o build/temp.linux-x86_64-pypy310/py/src/constraint.o -std=c++11
      g++ -pthread -DNDEBUG -O2 -fPIC -I/tmp/pip-build-env-9l5f03w9/overlay/lib/pypy3.10/site-packages/cppy/include -I. -I/home/runner/work/_temp/b89c2904-6e90-4eaf-9a37-51acc283b398/pypy-c-jit-185000-7d940def6f6b-linux64/include/pypy3.10 -c py/src/expression.cpp -o build/temp.linux-x86_64-pypy310/py/src/expression.o -std=c++11
      g++ -pthread -DNDEBUG -O2 -fPIC -I/tmp/pip-build-env-9l5f03w9/overlay/lib/pypy3.10/site-packages/cppy/include -I. -I/home/runner/work/_temp/b89c2904-6e90-4eaf-9a37-51acc283b398/pypy-c-jit-185000-7d940def6f6b-linux64/include/pypy3.10 -c py/src/kiwisolver.cpp -o build/temp.linux-x86_64-pypy310/py/src/kiwisolver.o -std=c++11
      g++ -pthread -DNDEBUG -O2 -fPIC -I/tmp/pip-build-env-9l5f03w9/overlay/lib/pypy3.10/site-packages/cppy/include -I. -I/home/runner/work/_temp/b89c2904-6e90-4eaf-9a37-51acc283b398/pypy-c-jit-185000-7d940def6f6b-linux64/include/pypy3.10 -c py/src/solver.cpp -o build/temp.linux-x86_64-pypy310/py/src/solver.o -std=c++11
      g++ -pthread -DNDEBUG -O2 -fPIC -I/tmp/pip-build-env-9l5f03w9/overlay/lib/pypy3.10/site-packages/cppy/include -I. -I/home/runner/work/_temp/b89c2904-6e90-4eaf-9a37-51acc283b398/pypy-c-jit-185000-7d940def6f6b-linux64/include/pypy3.10 -c py/src/strength.cpp -o build/temp.linux-x86_64-pypy310/py/src/strength.o -std=c++11
      g++ -pthread -DNDEBUG -O2 -fPIC -I/tmp/pip-build-env-9l5f03w9/overlay/lib/pypy3.10/site-packages/cppy/include -I. -I/home/runner/work/_temp/b89c2904-6e90-4eaf-9a37-51acc283b398/pypy-c-jit-185000-7d940def6f6b-linux64/include/pypy3.10 -c py/src/term.cpp -o build/temp.linux-x86_64-pypy310/py/src/term.o -std=c++11
      g++ -pthread -DNDEBUG -O2 -fPIC -I/tmp/pip-build-env-9l5f03w9/overlay/lib/pypy3.10/site-packages/cppy/include -I. -I/home/runner/work/_temp/b89c2904-6e90-4eaf-9a37-51acc283b398/pypy-c-jit-185000-7d940def6f6b-linux64/include/pypy3.10 -c py/src/variable.cpp -o build/temp.linux-x86_64-pypy310/py/src/variable.o -std=c++11
      Traceback (most recent call last):
        File "/home/runner/work/_temp/b89c2904-6e90-4eaf-9a37-51acc283b398/pypy-c-jit-185000-7d940def6f6b-linux64/lib/pypy3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/runner/work/_temp/b89c2904-6e90-4eaf-9a37-51acc283b398/pypy-c-jit-185000-7d940def6f6b-linux64/lib/pypy3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/runner/work/_temp/b89c2904-6e90-4eaf-9a37-51acc283b398/pypy-c-jit-185000-7d940def6f6b-linux64/lib/pypy3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-9l5f03w9/overlay/lib/pypy3.10/site-packages/setuptools/build_meta.py", line 415, in build_wheel
          return self._build_with_temp_dir(
        File "/tmp/pip-build-env-9l5f03w9/overlay/lib/pypy3.10/site-packages/setuptools/build_meta.py", line 397, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-9l5f03w9/overlay/lib/pypy3.10/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 46, in <module>
        File "/tmp/pip-build-env-9l5f03w9/overlay/lib/pypy3.10/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-9l5f03w9/overlay/lib/pypy3.10/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-9l5f03w9/overlay/lib/pypy3.10/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-9l5f03w9/overlay/lib/pypy3.10/site-packages/setuptools/_distutils/dist.py", line 964, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-9l5f03w9/overlay/lib/pypy3.10/site-packages/setuptools/dist.py", line 945, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-9l5f03w9/overlay/lib/pypy3.10/site-packages/setuptools/_distutils/dist.py", line 983, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-9l5f03w9/overlay/lib/pypy3.10/site-packages/setuptools/command/bdist_wheel.py", line 373, in run
          self.run_command("build")
        File "/tmp/pip-build-env-9l5f03w9/overlay/lib/pypy3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-9l5f03w9/overlay/lib/pypy3.10/site-packages/setuptools/dist.py", line 945, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-9l5f03w9/overlay/lib/pypy3.10/site-packages/setuptools/_distutils/dist.py", line 983, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-9l5f03w9/overlay/lib/pypy3.10/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-9l5f03w9/overlay/lib/pypy3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-9l5f03w9/overlay/lib/pypy3.10/site-packages/setuptools/dist.py", line 945, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-9l5f03w9/overlay/lib/pypy3.10/site-packages/setuptools/_distutils/dist.py", line 983, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-9l5f03w9/overlay/lib/pypy3.10/site-packages/setuptools/command/build_ext.py", line 93, in run
          _build_ext.run(self)
        File "/tmp/pip-build-env-9l5f03w9/overlay/lib/pypy3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "/tmp/pip-build-env-9l5f03w9/overlay/lib/pypy3.10/site-packages/cppy/__init__.py", line 56, in build_extensions
          build_ext.build_extensions(self)
        File "/tmp/pip-build-env-9l5f03w9/overlay/lib/pypy3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 476, in build_extensions
          self._build_extensions_serial()
        File "/tmp/pip-build-env-9l5f03w9/overlay/lib/pypy3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 502, in _build_extensions_serial
          self.build_extension(ext)
        File "/tmp/pip-build-env-9l5f03w9/overlay/lib/pypy3.10/site-packages/setuptools/command/build_ext.py", line 254, in build_extension
          _build_ext.build_extension(self, ext)
        File "/tmp/pip-build-env-9l5f03w9/overlay/lib/pypy3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 581, in build_extension
          self.compiler.link_shared_object(
        File "/tmp/pip-build-env-9l5f03w9/overlay/lib/pypy3.10/site-packages/setuptools/_distutils/ccompiler.py", line 757, in link_shared_object
          self.link(
        File "/tmp/pip-build-env-9l5f03w9/overlay/lib/pypy3.10/site-packages/setuptools/_distutils/unixccompiler.py", line 268, in link
          linker = (
      TypeError: 'NoneType' object is not subscriptable (key slice(None, None, None))
      [end of output]
```

</details>

Here is a successful build from same pr, but on a different nightly build:
https://github.com/mpmath/mpmath/actions/runs/10363788745/job/28688006957

Note that setuptools version difference is irrelevant here, same problem appears on setuptools<72.2.0.

**Comment by mattip** [comment]
kiwisolver is built with build isolation, so it brings its own versions of [setuptools and other dependencies](https://github.com/nucleic/kiwi/blob/df19e1839069ad0ad35b40e2e1e91aea44848902/pyproject.toml#L40C45-L40C65). It seems at the [point of failure](https://github.com/pypa/distutils/blob/8993718731b951ee36d08cb784f02aa13542ce15/distutils/unixccompiler.py#L272) `self.linker_so_cxx` is `None`, where it should be a list. I think this is due to some recent changes in distutils. Yay for not pinning upper versions of dependencies.

**Comment by skirpichev** [comment]
Hmm, it seems building kiwisolver was successful, yet I got a new failure on this build:
https://github.com/mpmath/mpmath/actions/runs/10401351060/job/28803717786?pr=839

I doubt it could be workarounded by pinning pytest.

<details>

```
  pytest
  shell: /usr/bin/bash -e {0}
  env:
    PYTEST_ADDOPTS: -n auto
    pythonLocation: /home/runner/work/_temp/98d44e71-00af-41e6-b6f3-440677322c83/pypy-c-jit-185020-f696301150f9-linux64
    Python_ROOT_DIR: /home/runner/work/_temp/98d44e71-00af-41e6-b6f3-440677322c83/pypy-c-jit-185020-f696301150f9-linux64
    Python2_ROOT_DIR: /home/runner/work/_temp/98d44e71-00af-41e6-b6f3-440677322c83/pypy-c-jit-185020-f696301150f9-linux64
    Python3_ROOT_DIR: /home/runner/work/_temp/98d44e71-00af-41e6-b6f3-440677322c83/pypy-c-jit-185020-f696301150f9-linux64
    PKG_CONFIG_PATH: /home/runner/work/_temp/98d44e71-00af-41e6-b6f3-440677322c83/pypy-c-jit-185020-f696301150f9-linux64/bin/lib/pkgconfig
Error calling sys.excepthook:
============================= test session starts ==============================
platform linux -- Python 3.10.14[pypy-7.3.17-alpha], pytest-8.3.2, pluggy-1.5.0
mpmath backend: python
mpmath mp class: <mpmath.ctx_mp.MPContext object at 0x00000000024aa598>
mpmath version: 1.4.0a2.dev76+g43fddbd
Python version: 3.10.14 (f696301150f9, Aug 15 2024, 06:03:35)
[PyPy 7.3.17-alpha0 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)]
rootdir: /home/runner/work/mpmath/mpmath
configfile: pyproject.toml
testpaths: mpmath, docs
plugins: hypothesis-6.111.0, cov-5.0.0, xdist-3.6.1
created: 4/4 workers
4 workers [339 items]


============================ no tests ran in 4.76s =============================
TypeError: PatchedTracebackException.format() got an unexpected keyword argument 'colorize'

Original exception was:
TypeError: PatchedTracebackException.format() got an unexpected keyword argument 'colorize'
```

</details>

Should I close this and open a new issue?

**Comment by devdanzin** [comment]
Seems to be related to #5003, where colorize was added.

**Comment by skirpichev** [comment]
Oh, is this was backported to 3.10?  If so, this looks as a bad idea to me: CPython's pyrepl - extremely buggy.  (I wish if 3.13 has this turned off by default.)

**Comment by cfbolz** [comment]
Ah, I can probably fix that specific error, I should be able to get to that in the next few days.

(Note however that pyrepl is actually PyPy's code since basically forever. CPython has forked it. We only backported a few of CPython's new features, including colorization. Do you have specific bugs in pyrepl that you'd like fixed?)

**Comment by mattip** [comment]
Bleh. The error is coming from [exceptiongroup](https://github.com/agronholm/exceptiongroup/blob/886bbede6912a0c9820f6d73f99ca0337b022871/src/exceptiongroup/_formatting.py#L218), which is only [installed by pytest](https://github.com/pytest-dev/pytest/blob/b08b41cefb5e83271a055bf6a22c79d52a06a8c3/pyproject.toml#L50) on python<3.11. PyPy's [`sys.excepthook`](https://github.com/pypy/pypy/blob/f696301150f9b7a7a7e52e1a3865bcdbca2a8923/pypy/module/sys/app.py#L60) is using `colorize` in the `format()` call. That won't work in combination with a monkey-patched `traceback.TracebackException` whose format does not support `colorize`.

**Comment by mattip** [comment]
Somehow CPython avoids this, I see exceptiongroup [has python3.13](https://github.com/agronholm/exceptiongroup/blob/886bbede6912a0c9820f6d73f99ca0337b022871/.github/workflows/test.yml#L38) tests?

**Comment by mattip** [comment]
Ahh, exceptiongroup [limits itself](https://github.com/agronholm/exceptiongroup/blob/886bbede6912a0c9820f6d73f99ca0337b022871/src/exceptiongroup/__init__.py#L18) when `python>=3.11`

**Comment by cfbolz** [comment]
@mattip 
> Ahh, exceptiongroup [limits itself](https://github.com/agronholm/exceptiongroup/blob/886bbede6912a0c9820f6d73f99ca0337b022871/src/exceptiongroup/__init__.py#L18) when `python>=3.11`

Yeah, it's a backport to pypi of a 3.11 feature.

But I'm already working on a patch anyway that gets rid of that extra argument, so the problem should go away soon.

**Comment by mattip** [comment]
The port of cpython#123062 landed in 1ebb72ae99

**Comment by mattip** [comment]
The [latest nightly 185023-99e76bf7a40b-linux64](https://github.com/mpmath/mpmath/actions/runs/10429950566/job/28887952395#step:4:32) is being used in the mpmath CI run, but it is still failing with [`TypeError: PatchedTracebackException.format() got an unexpected keyword argument 'colorize'`](https://github.com/mpmath/mpmath/actions/runs/10429950566/job/28887952395#step:10:32)

**Comment by mattip** [comment]
I added a failing test in 81eb5ae95b that I think mimics the problem

**Comment by cfbolz** [comment]
@mattip thanks, I'll take a look tomorrow (there's still a pr to CPython open that might go with yet another but probably even better variant, hopefully they merge it soon)

**Comment by mattip** [comment]
The latest nightly (from tomorrow) should work now.

**Comment by skirpichev** [comment]
Nightly builds aren't used now in mpmath CI, but I did tests in my fork.  I confirm, this is fixed.
